/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.thrift;

import com.example.thrift.ThriftService.Processor;

import org.apache.thrift.server.TServer;
import org.apache.thrift.server.TSimpleServer;
import org.apache.thrift.server.TThreadPoolServer;
import org.apache.thrift.transport.TServerSocket;
import org.apache.thrift.transport.TServerTransport;
import org.apache.thrift.transport.TTransportException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws TTransportException {
        ThriftService.AsyncIface handler = new ThriftServiceImpl();
        ThriftService.AsyncProcessor processor = new ThriftService.AsyncProcessor(handler);
        TServerTransport serverTransport = new TServerSocket(9090);
        TServer server = new TThreadPoolServer(new TThreadPoolServer.Args(serverTransport).processor(processor));
        server.serve();
    }
}
